### PR TITLE
loadAssets and loadMeta functions with meta, twitter, fb

### PR DESCRIPTION
**Pull request by carlwood**

### CODE REVIEW

**Review by shauunhimseelf — APPROVED** [review]

**Comment by hellopablo** [comment]
This looks fine but need to have a wee think about how we implement this kind of opinionated stuff. Will merge once we've had a bit of a discussion about where the line is.

**Comment by carlwood** [comment]
@hellopablo What's the opinionated stuff here?

**Comment by hellopablo** [comment]
Enforcing locations of favicons etc, @todos which will executable be left in production.

I'd rather see the skeleton transition to completely bare, no bootstrap, or gulp files etc and then fork a Shed version which we can put in our processes etc.

**Comment by hellopablo** [comment]
Late reviewing this, but will merge just now - we cans trip this back out again when we can facilitate a Shed fork of the skeleton.

**Pull request merged**
